version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: stock_box
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stock_box
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stock_network

  app:
    build: .
    container_name: my_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: stock_box
    depends_on:
      - postgres
    networks:
      - stock_network

volumes:
  pgdata:

networks:
  stock_network:
    driver: bridge
